const states = [
  {
    id: "0",
    name: "Select a state",
    pH: "1",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "1",
    name: "Andar Pradesh",
    pH: "7",
    phosphorus: "10.5",
    potassium: "6.33",
    nitrogen: "1",
  },
  {
    id: "2",
    name: "Arunachal Pradesh",
    pH: "5",
    phosphorus: "5",
    potassium: "2.5",
    nitrogen: "1",
  },
  {
    id: "3",
    name: "Assam",
    pH: "5",
    phosphorus: "3",
    potassium: "5",
    nitrogen: "1",
  },
  {
    id: "4",
    name: "Bihar",
    pH: "5.6",
    phosphorus: "13",
    potassium: "9",
    nitrogen: "1",
  },
  {
    id: "5",
    name: "Chandigarh",
    pH: "8.2",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "6",
    name: "Dadar & Nagar Haveli",
    pH: "7",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "7",
    name: "Delhi",
    pH: "5.5",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "8",
    name: "Goa",
    pH: "6",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "9",
    name: "Gujarat",
    pH: "7.67",
    phosphorus: "9.5",
    potassium: "9.5",
    nitrogen: "1",
  },
  {
    id: "10",
    name: "Haryana",
    pH: "8",
    phosphorus: "5.5",
    potassium: "5.5",
    nitrogen: "1",
  },
  {
    id: "11",
    name: "Himachal Pradesh",
    pH: "6.5",
    phosphorus: "3.66",
    potassium: "4.33",
    nitrogen: "1",
  },
  {
    id: "12",
    name: "Jammu & Kashmir",
    pH: "6.5",
    phosphorus: "5",
    potassium: "5",
    nitrogen: "1",
  },
  {
    id: "13",
    name: "Karnataka",
    pH: "5.22",
    phosphorus: "9.5",
    potassium: "6.66",
    nitrogen: "1",
  },
  {
    id: "14",
    name: "Kerala",
    pH: "5.25",
    phosphorus: "5",
    potassium: "5",
    nitrogen: "1",
  },
  {
    id: "15",
    name: "Madhya Pradesh",
    pH: "7",
    phosphorus: "22.5",
    potassium: "14.66",
    nitrogen: "1",
  },
  {
    id: "16",
    name: "Maharashtra",
    pH: "6",
    phosphorus: "12.5",
    potassium: "12.5",
    nitrogen: "1",
  },
  {
    id: "17",
    name: "Manipur",
    pH: "5.54",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "18",
    name: "Meghalaya",
    pH: "4.76",
    phosphorus: "2",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "19",
    name: "Mizoram",
    pH: "5",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "20",
    name: "Nagaland",
    pH: "4.9",
    phosphorus: "6",
    potassium: "5",
    nitrogen: "1",
  },
  {
    id: "21",
    name: "Orissa",
    pH: "8",
    phosphorus: "6.5",
    potassium: "6.5",
    nitrogen: "1",
  },
  {
    id: "22",
    name: "Pondicherry",
    pH: "4.5",
    phosphorus: "1",
    potassium: "1",
    nitrogen: "1",
  },
  {
    id: "23",
    name: "Punjab",
    pH: "8.15",
    phosphorus: "6",
    potassium: "6",
    nitrogen: "1",
  },
  {
    id: "24",
    name: "Rajasthan",
    pH: "7",
    phosphorus: "8.66",
    potassium: "13",
    nitrogen: "1",
  },
  {
    id: "25",
    name: "Tamil Nadu",
    pH: "6",
    phosphorus: "6.5",
    potassium: "6.5",
    nitrogen: "1",
  },
  {
    id: "26",
    name: "Uttar Pradesh",
    pH: "7.72",
    phosphorus: "27.2",
    potassium: "18.66",
    nitrogen: "1",
  },
  {
    id: "27",
    name: "West Bengal",
    pH: "6.25",
    phosphorus: "7.5",
    potassium: "5.33",
    nitrogen: "1",
  },
  {
    id: "28",
    name: "Tripura",
    pH: "4.6",
    phosphorus: "3",
    potassium: "3",
    nitrogen: "1",
  },
];
export default states;
